version: '3.8'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - db:/data/db
    networks:
      - backend
  
  app:
    build: .
    restart: unless-stopped
    env_file: ./.env
    container_name: app
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_STRING=mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/
    networks:
      - backend
      - frontend

volumes: 
  db:

networks:
  backend:
  frontend:
